version: "1.0"
info:
  model: int-scaffold
packages:
- name: Mirs_ong_workspaceProject
  gitServerName: mir_github
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: main
- name: ChevronDemo
  version: "1.0"
  gitServerName: mir_github
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: master
- name: EmployeeHiringDemo
  gitServerName: mir_github
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: master
security:
- name: ChevronDemo
  allowedServices: []
  javaServiceSetting: ALL
